select top 10000 a.ENCOUNTER_ID, a.ACCESSION, a.FALSE_POSITIVE_IND,
 a.FIRST_REPORT_ENTERED_DT_TM, a.ISOLATE_ID, a.LAST_REPORT_UPDATED_DT_TM, 
 a.MICRO_LAB_COMPLETED_DT_TM,a.MICRO_LAB_CANCELLED_DT_TM, a.MICRO_LAB_DRAWN_DT_TM,
 a.MICRO_LAB_ORDERED_DT_TM, a.MICRO_LAB_RECEIVED_DT_TM, a.ORDERING_PHYSICIAN_ID,
 a.REPORTING_PRIORITY_ID, a.TOTAL_REPORT_UPDATES, f.MICRO_RESULT_TYPE_DESC, f.MICRO_RESULT_TYPE_CODE,
 b.ISOLATE_TYPE, b.ISOLATE_CATEGORY, b.ISOLATE_REPT_CATEGORY, b.ISOLATE_GROUP, b.ISOLATE_NAME, 
 c.LAB_PROCEDURE_NAME, 
d.COLLECTION_SOURCE_SITE_DESC as COLLECTION_SOURCE_DESC, 
e.COLLECTION_SOURCE_SITE_DESC as COLLECTION_SITE_DESC
from HealthFacts.dbo.HF_F_Microbiology_2017 a
inner join
(select * from HealthFacts.dbo.HF_D_ISOLATE where ISOLATE_NAME not in ('NULL', 'Not Mapped')) b
on a.isolate_id=b.ISOLATE_ID
left join
HealthFacts.dbo.HF_D_LAB_PROCEDURE c
on a.ORDER_LAB_PROCEDURE_ID=c.LAB_PROCEDURE_ID
left join
HealthFacts.dbo.HF_D_COLLECTION_SRC_SITE d
on a.COLLECTION_SOURCE_ID=d.COLLECTION_SOURCE_SITE_ID
left join
HealthFacts.dbo.HF_D_COLLECTION_SRC_SITE e
on a.COLLECTION_SITE_ID=e.COLLECTION_SOURCE_SITE_ID
left join
HealthFacts.dbo.HF_D_MICRO_RESULT_TYPE f
on a.MICRO_RESULT_TYPE_ID=f.MICRO_RESULT_TYPE_ID